server:
  port: 7779
spring:
  datasource:
    url: jdbc:mysql://www.iamcrawler.cn:3306/docker_demo?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver